@baseUrl = http://localhost:5223

### 1. Register a new user
# @name register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Omar",
  "lastName": "Hassan",
  "email": "omar.hassan@example.com",
  "phoneNumber": "+201155500001",
  "password": "Omar@123456",
  "confirmPassword": "Omar@123456",
  "countryCode": "EG",
  "preferredLanguage": "English"
}

### 2. Login with the registered user
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "identifier": "omar.hassan@example.com",
  "password": "Omar@123456"
}

###

@accessToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NjI3NjJhOS1kZjgzLTQwYTAtOWZjYy1jZDc3ODE2ZDIzMmYiLCJqdGkiOiI0ZDE3MDQzZS05Njg0LTQwNzItOWY5ZC02ZDhkZjhmMzg5YWIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk2Mjc2MmE5LWRmODMtNDBhMC05ZmNjLWNkNzc4MTZkMjMyZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJPbWFyIEhhc3NhbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im9tYXIuaGFzc2FuQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbW9iaWxlcGhvbmUiOiIrMjAxMTU1NTAwMDAxIiwiZXhwIjoxNzg2Mzc3NTEzLCJpc3MiOiJGaXhOb3cuQXBpIiwiYXVkIjoiRml4Tm93LkNsaWVudCJ9.VEPjABh_O0o-tjjML3wTxfvPTQKLIUvOpTx-19qYPiE

### 3. Get the current user
GET {{baseUrl}}/api/users/me
Authorization: Bearer {{accessToken}}

### 4. Update the current user
PUT {{baseUrl}}/api/users/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "firstName": "Omar",
  "lastName": "Hassan",
  "email": "omar.hassan@example.com",
  "phoneNumber": "+201155500001",
  "countryCode": "EG",
  "preferredLanguage": "English"
}

### 5. Change the password
POST {{baseUrl}}/api/users/me/change-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "Omar@123456",
  "newPassword": "Omar@654321",
  "confirmPassword": "Omar@654321"
}

### 6. Deactivate the current user
DELETE {{baseUrl}}/api/users/me
Authorization: Bearer {{accessToken}}
